#### CSCE 670 :: Information Storage and Retrieval :: Texas A&M University :: Spring 2020


# Spotlight- Pandas - Yu Zhang

Pandas is a tool based on NumPy, which is created to solve data analysis tasks. You will soon discover that it is one of the important factors that makes Python a powerful and efficient data analysis environment.


 

## Data read and operation in Pandas
pandas mainly has two types of data structures, they are dataframe and series. I will focus on the dataframe
there are many ways for pandas to read file, the common way is to read data from CSV file. After read data as a dataframe. we can do serval operations here

head(),tail() display the first n records from dataframe

info(), describe(), columns()  display the information , describe and columns name of the dataframe.
describe() could only produce the report for numbers, it can not worked for data type object 

In [2]:
# The first step is to import the necessary lib


import csv
import pandas
import numpy as np
import sklearn
import re
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import matplotlib



In [24]:
f = open("csv.csv")
data = pandas.read_csv(f,encoding='utf-8')
print('the below is the function head')
data.head()


the below is the function head


passenger  flight mile   price departTime  arrivalTime  class    from   \
0         a         12312    132       15:00        16:00     A      lax   
1         b         13212    133        8:00        10:00     A      lax   
2         c         84727    333       17:00        19:00     B  beijing   
3         d          4523    400       20:00        22:00     C       ny   

           to  dicount  VIP  
0          ny      0.6    1  
1         sfo      1.0    0  
2         sfo      0.5    1  
3  cincinnati      0.8    0

In [25]:
print('the below is the function tail')
data.tail()

the below is the function tail


passenger  flight mile   price departTime  arrivalTime  class    from   \
0         a         12312    132       15:00        16:00     A      lax   
1         b         13212    133        8:00        10:00     A      lax   
2         c         84727    333       17:00        19:00     B  beijing   
3         d          4523    400       20:00        22:00     C       ny   

           to  dicount  VIP  
0          ny      0.6    1  
1         sfo      1.0    0  
2         sfo      0.5    1  
3  cincinnati      0.8    0

In [4]:
# return the number of records of the whole
print(data.index) 



RangeIndex(start=0, stop=4, step=1)


In [5]:
# display the basic information 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
passenger       4 non-null object
flight mile     4 non-null int64
price           4 non-null int64
departTime      4 non-null object
arrivalTime     4 non-null object
class           4 non-null object
from            4 non-null object
to              4 non-null object
dicount         4 non-null float64
VIP             4 non-null int64
dtypes: float64(1), int64(3), object(6)
memory usage: 448.0+ bytes


In [6]:
# display the describiton of the dataframe, notice! it could only work for number type
print(data.describe().T)

              count       mean           std     min        25%      50%  \
flight mile     4.0  28693.500  37558.827533  4523.0  10364.750  12762.0   
price           4.0    249.500    137.841697   132.0    132.750    233.0   
dicount         4.0      0.725      0.221736     0.5      0.575      0.7   
VIP             4.0      0.500      0.577350     0.0      0.000      0.5   

                   75%      max  
flight mile   31090.75  84727.0  
price           349.75    400.0  
dicount           0.85      1.0  
VIP               1.00      1.0  


In [7]:
#print the value of the key as an array
price_value = data["price"].values 
print(price_value)

[132 133 333 400]


Te next part we will do the searching among data using the function  isin() . The data to be filtered is put into a list, the data is filtered using isin, and the row index and the filtered results of each row are returned. If it matches, it returns true

The example below is to search the the data lax or ny in data column "to" 


In [8]:
chose = ["lax","ny"]
result=data["to"].isin(chose)
data[result]

passenger  flight mile   price departTime  arrivalTime  class from   to  \
0         a         12312    132       15:00        16:00     A   lax  ny   

   dicount  VIP  
0      0.6    1

## Data format change
if we want to change the data to specicifc data format, we need to run  pandas_tpdatetime to convert it to the specific time format

The example below is to change the date data to the required format  hours: minutes

In [26]:
data["departTime "]=pandas.to_datetime(data["departTime "], format="%H:%M")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
passenger       4 non-null object
flight mile     4 non-null int64
price           4 non-null int64
departTime      4 non-null datetime64[ns]
arrivalTime     4 non-null object
class           4 non-null object
from            4 non-null object
to              4 non-null object
dicount         4 non-null float64
VIP             4 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 448.0+ bytes


## How to prepare training data with Pandas
Here we will train a SVM classification.  Brfore that ,we need to prepare the data, the flight time (the difference between landing time and take-off time) is used to indirectly reflect the flight distance.

firstly we will read the data from CSV file

secondly replace the class with specific number 

Thridly ,we add one new column as the flight duration time using to_datetime funciton in Pandas


In [38]:
f = open("csv.csv")
data = pandas.read_csv(f,encoding="utf-8")


print("----------check siteclass----------------")
print(data["class"].unique()) 
change = {'A':0, 'B':1, 'C':2}
print(" ")
data["class"]=data["class"].replace(change)
print("class number with its count")
print(data['class'].value_counts())

----------check siteclass----------------
['A' 'B' 'C']
 
class number with its count
0    2
2    1
1    1
Name: class, dtype: int64


In [39]:
#calculate the duration time with Pandas
data['departTime ']=pandas.to_datetime(data['departTime '], format="%H:%M")
data['arrivalTime ']=pandas.to_datetime(data['arrivalTime '], format="%H:%M")
data.insert(loc=6,column="lasttime",value=0)
data["lasttime"] = data["arrivalTime "]-data["departTime "]
print(data["lasttime"])

0   01:00:00
1   02:00:00
2   02:00:00
3   02:00:00
Name: lasttime, dtype: timedelta64[ns]


##  Example:    Train SVM with data refined by Pandas

In this experienment, we will do SVMfor the flight mile, class to produce the label for test user.
to train SVM model , firstly we need to generate the matrix, we will extract data- flight duraton and class to generate the matrix using the concatenate function in the numpy 

In [11]:
siteclass = np.array(data["class"]).reshape([-1,1])
discount = np.array(data["dicount"]).reshape([-1,1])
VIPservice = np.array(data["VIP"]).reshape([-1,1])
minutes = []
for one in data["lasttime"]:
    minutes.append(one.seconds/60.0)
minutes = np.array(minutes).reshape([-1,1])
minutes = (minutes-minutes.min())/(minutes.max()-minutes.min())
train= np.concatenate([minutes, siteclass,discount],axis=1)
print(train)

[[0.  0.  0.6]
 [1.  0.  1. ]
 [1.  1.  0.5]
 [1.  2.  0.8]]


In [12]:
from sklearn.svm import SVC
clf = SVC(gamma='auto', C=1, probability=True)
label = data["VIP"]
clf.fit(train, label)
print(" finished train")



 finished train


Then we are going to test the data, as before we load the data using pandas and test with the model we trained

In [40]:
f = open("test.csv")
test = pandas.read_csv(f,encoding="utf-8")


siteclass = np.array(test["class"]).reshape([-1,1])
discount = np.array(test["discount"]).reshape([-1,1])
time = np.array(test["time"]).reshape([-1,1])
test= np.concatenate([time, siteclass,discount],axis=1)

y = clf.predict(test)
print(y)

[0 0 0]


##  GroupBy() and Transform()  in Pandas

Pandas dataframe.groupby() function is used to split the data into groups based on some criteria. pandas objects can be split on any of their axes. The abstract definition of grouping is to provide a mapping of labels to group names.

Parameters :
by : mapping, function, str, or iterable
axis : int, default 0
level : If the axis is a MultiIndex (hierarchical), group by a particular level or levels
as_index : For aggregated output, return object with group labels as the index. Only relevant for DataFrame input. as_index=False is effectively “SQL-style” grouped output
sort : Sort group keys. Get better performance by turning this off. Note this does not influence the order of observations within each group. groupby preserves the order of rows within each group.
group_keys : When calling apply, add group keys to index to identify pieces
squeeze : Reduce the dimensionality of the return type if possible, otherwise return a consistent type

Returns : GroupBy object

Now let's run the example to see how it work

In [16]:
frame = pandas.DataFrame({'key':['a','s','a','f'],'value':range(4)})
print(frame)
ele= frame.groupby('key').agg(['sum'])
print(ele)


  key  value
0   a      0
1   s      1
2   a      2
3   f      3
    value
      sum
key      
a       2
f       3
s       1


In the example above by the function groupBy, we could calculate the sum of each key and list the result with aggregation

If I wish I could merge the data, instead of merging the data and then merging the tables, and the calculated data is written next to each of the same kind, then we need the transform () function

Aggregation will return a reduced version of the data, and transformation can return a transformed version of the complete data for us to reorganize. In this transformation, the shape of the output is the same as the input. Here is a example to show how to use the function transform()

In [17]:
ele = frame.groupby('key')
test = ele.transform(lambda x : x.sum())
print(test)

   value
0      2
1      1
2      2
3      3


from the example we could see that the output is same as input there are four key in the input, so the output also has 4 keys

sum of key a is 2
sum of key b is 1 
sum of key a is 2
sum of key f is 3

thus we have four output


##  GroupBy()  with date data 

For general characters, strings, and numbers, we can use groupby to easily isolate the data. But for logarithmic time data, the way we want to distinguish him is to introduce the TimeGroup object and the resample method

The resample method is to separate the index data by resample, and the time data is the key on the index.


the below is an example

In [21]:
# generate time data
time = pandas.date_range('2019/7/12 00:00',freq='5min',periods=10)
print(time)
print(' ')
frame = pandas.DataFrame({'time':time,'value':range(10)})
print(frame)

DatetimeIndex(['2019-07-12 00:00:00', '2019-07-12 00:05:00',
               '2019-07-12 00:10:00', '2019-07-12 00:15:00',
               '2019-07-12 00:20:00', '2019-07-12 00:25:00',
               '2019-07-12 00:30:00', '2019-07-12 00:35:00',
               '2019-07-12 00:40:00', '2019-07-12 00:45:00'],
              dtype='datetime64[ns]', freq='5T')
 
                 time  value
0 2019-07-12 00:00:00      0
1 2019-07-12 00:05:00      1
2 2019-07-12 00:10:00      2
3 2019-07-12 00:15:00      3
4 2019-07-12 00:20:00      4
5 2019-07-12 00:25:00      5
6 2019-07-12 00:30:00      6
7 2019-07-12 00:35:00      7
8 2019-07-12 00:40:00      8
9 2019-07-12 00:45:00      9


Then we are going to separate the data with 20 minutes as the gap

In [22]:
test = frame.set_index('time').resample('20min').count()
print(test)

                     value
time                      
2019-07-12 00:00:00      4
2019-07-12 00:20:00      4
2019-07-12 00:40:00      2


As we can see we could group the date data with 20 minutes as the gap

## Summary

With the help of Pandas, we could do data analysis quickly. It could provide us many API to handle the data like date , time ,hours. It could also provide us some useful functions like transform , groupBy.

